package ProgTools;

/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

 /*
 * Scoring_Assistant.java
 *
 * Created on Apr 19, 2011, 4:48:42 PM
 */
import ij.IJ;
import static ij.IJ.selectWindow;
import ij.ImageListener;
import ij.ImagePlus;
import ij.ImageStack;
import ij.VirtualStack;
import ij.WindowManager;
import ij.gui.ImageCanvas;
import ij.gui.ImageWindow;
import ij.gui.StackWindow;
import ij.measure.Calibration;
import ij.measure.ResultsTable;
import ij.plugin.ImageCalculator;
import ij.plugin.PlugIn;
import ij.process.ImageProcessor;
import ij.text.TextWindow;
import java.awt.Component;
import java.awt.event.KeyEvent;
import java.awt.event.KeyListener;
import java.awt.event.MouseEvent;
import java.awt.event.MouseListener;
import java.awt.event.MouseMotionListener;
import java.awt.image.BufferedImage;
import java.io.ByteArrayInputStream;
import java.io.File;
import java.io.IOException;
import java.io.InputStream;
import java.util.Arrays;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.imageio.ImageIO;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.UIManager;
import org.opencv.core.Core;
import org.opencv.core.CvType;
import org.opencv.core.Mat;
import org.opencv.core.MatOfByte;
import org.opencv.imgcodecs.Imgcodecs;
import org.opencv.videoio.VideoCapture;
import static org.opencv.videoio.Videoio.*;

/**
 *
 * @author Every one
 */
public class Scoring_Assistant extends java.awt.Frame implements MouseListener, KeyListener, Runnable {

    File DataFile, ImgFile = null;
    VideoReader vr = null;
    ImageStack Stack = null;
    ImagePlus imp = null;
    boolean Error = false;
    private int nFrames = 0;  //Total number of frames in the image seq
    private int nScoringFrames = 30;  //Number of consequitive frames to score
    private File BgdFile;       // Place to store the background image file
    private ImagePlus bgdimp;
    private ImagePlus Signal;
    private ResultsTable rt;
    private ImageCanvas previousCanvas = null;
    private boolean mFlag = false;
    private boolean kFlag = false;
    private boolean reentry = false;
    private Component frame;
    VideoCapture cap = null;
    Thread scoreAssist = null;

    /**
     * Creates new form Scoring_Assistant
     */
    public Scoring_Assistant() {
        try {
            UIManager.setLookAndFeel(UIManager.getSystemLookAndFeelClassName());
        } catch (Exception e) {
            System.out.println("Error setting native LAF: " + e);
        }
        initComponents();

        //WindowManager.addWindow(this);
        this.setVisible(true);
//        ij.IJ.showMessage("Test title", "Test body: This is how imagej dialog box appears.");

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Progress = new javax.swing.JFrame();
        SeqProgress = new javax.swing.JProgressBar();
        OverAllProgressBar = new javax.swing.JProgressBar();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        NxtSeq = new javax.swing.JButton();
        AutoAdvStat = new javax.swing.JCheckBox();
        StopScore = new javax.swing.JButton();
        startScore = new javax.swing.JButton();
        nImgs = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        nImgAdv = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        mThreshold = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        nConsecutive = new javax.swing.JTextField();
        DataBrowse = new javax.swing.JButton();
        ResultBrowse = new javax.swing.JButton();
        Score = new javax.swing.JButton();
        nPeople = new javax.swing.JSpinner();
        SetBgd = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        SubBgd = new javax.swing.JButton();

        Progress.setTitle("Progress..");
        Progress.setBounds(new java.awt.Rectangle(0, 0, 300, 250));

        jLabel6.setText("Over All Progress");

        jLabel7.setText("Progress in sequence..");

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Seq. Navigation"));

        NxtSeq.setText("Next Seq");
        NxtSeq.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NxtSeqActionPerformed(evt);
            }
        });

        AutoAdvStat.setText("Auto Advance");
        AutoAdvStat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AutoAdvStatActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(AutoAdvStat)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 35, Short.MAX_VALUE)
                .addComponent(NxtSeq, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(AutoAdvStat, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(NxtSeq, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        StopScore.setText("Stop scoring");
        StopScore.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                StopScoreActionPerformed(evt);
            }
        });

        startScore.setText("Start scoring");

        javax.swing.GroupLayout ProgressLayout = new javax.swing.GroupLayout(Progress.getContentPane());
        Progress.getContentPane().setLayout(ProgressLayout);
        ProgressLayout.setHorizontalGroup(
            ProgressLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ProgressLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(ProgressLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(OverAllProgressBar, javax.swing.GroupLayout.DEFAULT_SIZE, 453, Short.MAX_VALUE)
                    .addComponent(jLabel6)
                    .addComponent(SeqProgress, javax.swing.GroupLayout.DEFAULT_SIZE, 453, Short.MAX_VALUE)
                    .addComponent(jLabel7)
                    .addGroup(ProgressLayout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(32, 32, 32)
                        .addGroup(ProgressLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(StopScore, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(startScore, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap())
        );
        ProgressLayout.setVerticalGroup(
            ProgressLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ProgressLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(OverAllProgressBar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel7)
                .addGap(11, 11, 11)
                .addComponent(SeqProgress, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(ProgressLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(ProgressLayout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(27, 27, 27))
                    .addGroup(ProgressLayout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addComponent(startScore)
                        .addGap(15, 15, 15)
                        .addComponent(StopScore)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );

        setBackground(new java.awt.Color(236, 233, 216));
        setTitle("Scoring Assistant");
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                exitForm(evt);
            }
        });

        jLabel1.setText("Number of Images to score");

        jLabel2.setText("Motion Threshold");

        jLabel3.setText("Number of frames to advance");

        nImgAdv.setText("5");

        jLabel4.setText("Number of people scoring");

        jLabel5.setText("Number of consecutive frames");

        DataBrowse.setText("Select Data file");
        DataBrowse.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DataBrowseActionPerformed(evt);
            }
        });

        ResultBrowse.setText("Export Results File");
        ResultBrowse.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ResultBrowseActionPerformed(evt);
            }
        });

        Score.setText("Start_Scoring");
        Score.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ScoreActionPerformed(evt);
            }
        });

        nPeople.setModel(new javax.swing.SpinnerNumberModel(1, 0, 2, 1));

        SetBgd.setText("Select Background");
        SetBgd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SetBgdActionPerformed(evt);
            }
        });

        jButton1.setText("Generate Background");

        SubBgd.setText("Substract Background");
        SubBgd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SubBgdActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(jLabel1)
                    .addComponent(jLabel5)
                    .addComponent(jLabel2)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(nConsecutive, 0, 1, Short.MAX_VALUE)
                        .addComponent(mThreshold, 0, 1, Short.MAX_VALUE)
                        .addComponent(nImgAdv, javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(nImgs, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(nPeople, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(17, 17, 17))
            .addGroup(layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(DataBrowse, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(SetBgd, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(Score, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(ResultBrowse, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(SubBgd)
                    .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(92, 92, 92)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel3))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(nImgs, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(nImgAdv, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(nPeople, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4))
                        .addGap(34, 34, 34)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(mThreshold, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(nConsecutive, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 29, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(DataBrowse)
                    .addComponent(SetBgd)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Score)
                    .addComponent(ResultBrowse)
                    .addComponent(SubBgd))
                .addGap(47, 47, 47))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * Exit the Application
     */
    private void exitForm(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_exitForm
        System.exit(0);
    }//GEN-LAST:event_exitForm

    private void DataBrowseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DataBrowseActionPerformed
        //'Select Data file' button
//        this.testMethod();
//System.loadLibrary(Core.NATIVE_LIBRARY_NAME);

//Step1: Select file through file chooser
        JFileChooser Fc = new JFileChooser();
        Fc.setMultiSelectionEnabled(false);
        Fc.setVisible(true);
        int result = Fc.showOpenDialog(null);
        if (result == JFileChooser.APPROVE_OPTION) {
            ImgFile = Fc.getSelectedFile();
//Step2: Open selected file using opencv
            if (ImgFile.exists() && ImgFile.isFile()) {
                vr = new VideoReader(ImgFile);
                vr.setStackBuff();
                imp = vr.getStackBuff();
                imp.show();
            } else {
                Error = true;
                ij.IJ.showMessage("Error", "Error with file.");
            }
        } else
            Error = true;
    }//GEN-LAST:event_DataBrowseActionPerformed

    private void ResultBrowseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ResultBrowseActionPerformed
        //'Export Results file' button
        JFileChooser res = new JFileChooser();
        res.setDialogType(JFileChooser.SAVE_DIALOG);
        res.setVisible(true);
        res.showSaveDialog(res);
        ij.IJ.showMessage("ERROR", "File not saved. Save file using Results Table save option.");
        //File
        //Code to save rt missing?
        //TO DO: Add code to save rt.
        //Currently, rt has to be saved using rt menu bar's save button.

    }//GEN-LAST:event_ResultBrowseActionPerformed

    private void ScoreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ScoreActionPerformed
        //'Start_Scoring' button
        System.out.println("ScoreAction btn clicked");
//        new Thread(vr).run();
        vr.setStackBuff();      
        nFrames = (int) vr.totalFrames;
        imp = vr.getStackBuff();
        imp.show();

        Progress.toFront();
        AutoAdvStat.setSelected(false);
        Progress.setVisible(true);
        OverAllProgressBar.setMinimum(0);
        OverAllProgressBar.setMaximum(nFrames);
        OverAllProgressBar.setValue(imp.getCurrentSlice());

        SeqProgress.setMinimum(0);
        SeqProgress.setMaximum(nFrames);

        rt = new ResultsTable();
        rt.show("Score");
//        TextWindow rtw = rt.getResultsWindow();
//        System.out.println(rtw.getClass());
//        System.out.println(rtw.getSize());
//        System.out.println(rtw.getLocation());
//        rtw.setLocation(0, 0);
//        ij.IJ.showMessage("Test title", "RT should be at top left corner.");

        reentry = false;
        //for(int count = 0 ; count < rt.addColumns();


    }//GEN-LAST:event_ScoreActionPerformed

    private void AutoAdvStatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AutoAdvStatActionPerformed
        //'Auto advance' check box
        NxtSeq.setEnabled(!AutoAdvStat.isSelected());
        System.out.println("AutoAdvance before selected");
        if (AutoAdvStat.isSelected()) {
            System.out.println("In if condition");
            if (imp != null) {
                ImageWindow win = imp.getWindow();
                win.toFront();
                win.removeKeyListener(IJ.getInstance());
                win.removeKeyListener(IJ.getInstance());
                win.addKeyListener(this);
                ImageCanvas canvas = imp.getCanvas();
                int i = 1;
                canvas.disablePopupMenu(true);
                if (canvas != previousCanvas) {
                    if (previousCanvas != null) {
                        previousCanvas.removeMouseListener(this);
                    }
                    canvas.addMouseListener(this);
                    // canvas.addKeyListener(this);
                    previousCanvas = canvas;
                }
            } else {
                if (previousCanvas != null) {
                    previousCanvas.removeMouseListener(this);
                }
                previousCanvas = null;
            }
            this.NxtSeqActionPerformed(null);
        }


    }//GEN-LAST:event_AutoAdvStatActionPerformed

    private void SetBgdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SetBgdActionPerformed
        //'Set Background' button
        JFileChooser FC = new JFileChooser();
        int result = FC.showOpenDialog(null);

        if (result == JFileChooser.APPROVE_OPTION) {
            BgdFile = FC.getSelectedFile();
            if (BgdFile.exists() && BgdFile.isFile()) {
                bgdimp = new ImagePlus(BgdFile.getPath());
            }
            if (bgdimp == null) {
                Error = true;
            } else {
                Stack = bgdimp.getImageStack();
                int bgdSz = Stack.getSize();
                if (nFrames < bgdSz) {
                    ij.IJ.showMessage("Error: Stack mismatch", "The number of frames in background does not match the image stack. Using the first slice and ignoring the rest");
                    while (Stack.getSize() > 1) {
                        Stack.deleteLastSlice();
                    }
                }
                bgdimp.show();
            }
        } else {
            Error = true;
        }

        // TODO add your handling code here:
    }//GEN-LAST:event_SetBgdActionPerformed

    private void NxtSeqActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NxtSeqActionPerformed
        // TODO:
        //check if overallprogressbar has reached maximum. if yes, set reentry to false.
//        OverAllProgressBar.setValue(imp.getCurrentSlice());
        Integer advance = new Integer(nImgAdv.getText());
        OverAllProgressBar.setValue(OverAllProgressBar.getValue() + advance);
        rt.incrementCounter();

        //rt.show("Score");
        reentry = true;
        scoreAssist = new Thread(this);
        scoreAssist.start();
        new Thread(vr).start();

//        ImageWindow win = imp.getWindow();
////        win.setImage(vr.getStackBuff());


        imp.show();
        System.out.println("End of nxtseqaction");

    }//GEN-LAST:event_NxtSeqActionPerformed

    private void SubBgdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SubBgdActionPerformed
        //'Subtract background' button
        int bSlices = bgdimp.getCurrentSlice();
        ImagePlus curSlice;
        ImageStack Stack = imp.getStack();
        ImageStack resStack = new ImageStack(Stack.getWidth(), Stack.getHeight());
        ImageCalculator Calc = new ImageCalculator();
        String imageTitle = imp.getTitle();
        Calibration cal = imp.getCalibration();
        int maxSlice = Stack.getSize();
        boolean status = true;
        if (bSlices == 1) {
            for (int count = 1; count < maxSlice && status; count++) {
                curSlice = new ImagePlus(imageTitle, Stack.getProcessor(count));
                curSlice = Calc.run("Difference create", curSlice, bgdimp);

                resStack.addSlice(imageTitle, curSlice.getProcessor());

            }
            while (imp.getCurrentSlice() > 1) {
                Stack.deleteLastSlice();
            }
            imp.setStack(resStack);
            imp.show();
        } else {
            new ImageCalculator().run("Difference stack", imp, bgdimp);
        }
    }//GEN-LAST:event_SubBgdActionPerformed

    private void StopScoreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_StopScoreActionPerformed
        // TODO add your handling code here:
        ImageWindow win = imp.getWindow();
        win.removeMouseListener(this);
        win.removeKeyListener(this);
        win.addMouseListener(IJ.getInstance());
        win.addKeyListener(IJ.getInstance());
    }//GEN-LAST:event_StopScoreActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox AutoAdvStat;
    private javax.swing.JButton DataBrowse;
    private javax.swing.JButton NxtSeq;
    private javax.swing.JProgressBar OverAllProgressBar;
    private javax.swing.JFrame Progress;
    private javax.swing.JButton ResultBrowse;
    private javax.swing.JButton Score;
    private javax.swing.JProgressBar SeqProgress;
    private javax.swing.JButton SetBgd;
    private javax.swing.JButton StopScore;
    private javax.swing.JButton SubBgd;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField mThreshold;
    private javax.swing.JTextField nConsecutive;
    private javax.swing.JTextField nImgAdv;
    private javax.swing.JTextField nImgs;
    private javax.swing.JSpinner nPeople;
    private javax.swing.JButton startScore;
    // End of variables declaration//GEN-END:variables

    public void mouseClicked(MouseEvent e) {
        int row = rt.getCounter();
        //IJ.showMessage("Mouse Active");
        if (e.getButton() == e.BUTTON1) {
            rt.setValue("Mouse", row - 1, 1);
        } else if (e.getButton() == e.BUTTON2) {
            rt.setValue("Mouse", row - 1, 0);
        }
        rt.show("Score");
        if (AutoAdvStat.isSelected()) {
            mFlag = true;
            this.NxtSeqActionPerformed(null);
        }

    }

    public void mousePressed(MouseEvent e) {
        //throw new UnsupportedOperationException("Not supported yet.");
    }

    public void mouseReleased(MouseEvent e) {
        // throw new UnsupportedOperationException("Not supported yet.");
    }

    public void mouseEntered(MouseEvent e) {
        //throw new UnsupportedOperationException("Not supported yet.");
    }

    public void mouseExited(MouseEvent e) {
        //throw new UnsupportedOperationException("Not supported yet.");
    }

    public void keyTyped(KeyEvent e) {
        int row = rt.getCounter();
        if (e.getKeyChar() == 'y' || e.getKeyChar() == 'Y') {
            rt.setValue("Key", row - 1, 1);
        } else {
            rt.setValue("Key", row - 1, 0);
        }
        rt.show("Score");
        if (AutoAdvStat.isSelected()) {
            kFlag = true;
            this.NxtSeqActionPerformed(null);
        }

    }

    public void keyPressed(KeyEvent e) {
        IJ.getInstance().keyPressed(e);
    }

    public void keyReleased(KeyEvent e) {
        // throw new UnsupportedOperationException("Not supported yet.");
        IJ.getInstance().keyReleased(e);
    }

    public synchronized void run() {
        System.out.println("ScorAssist Thread RUN");

        Stack = imp.getStack();

        Integer advance = new Integer(nImgAdv.getText());
//        int cSlice = imp.getCurrentSlice();
        int cSlice = OverAllProgressBar.getValue();

         if(cSlice >= nFrames)
            return;
//        if (nFrames < imp.getCurrentSlice() + advance) {
//            return;
//        }

        SeqProgress.setMaximum(advance);

        Calibration cal = imp.getCalibration();
System.out.println("imp fps: " + cal.fps);
        long frameRate = 50;
        if (cal.fps != 0.0) {
            frameRate = (long) (1000.0 / cal.fps);
        }
        long timeInc = frameRate;
        ImageWindow win = imp.getWindow();
        //win = imp.getWindow();
        StackWindow swin = (StackWindow) win;
        swin.setAnimate(true);
        Thread.currentThread().setPriority(Thread.MIN_PRIORITY);

        long time = System.currentTimeMillis(), nextime = System.currentTimeMillis();
        // long stoptime = timeInc*advance.intValue();
        long timeDiff = nextime - time;

        for (int count = 0; count <= advance; count++) {
            SeqProgress.setValue(count);
            IJ.showStatus((int) (cal.fps + 0.5) + " fps");

            time = System.currentTimeMillis();
            if (time < nextime) {
                // IJ.wait((int)(nextime - time));
                try {
                    timeDiff = nextime - time;
                    Thread.currentThread().sleep(timeDiff);
                } catch (InterruptedException ex) {
                    Logger.getLogger(Scoring_Assistant.class.getName()).log(Level.SEVERE, null, ex);
                }
            } else {
                Thread.currentThread().yield();
                nextime += timeInc;
            }
//            swin.showSlice(cSlice + count);
            swin.showSlice(imp.getCurrentSlice() + count);

        }
//        OverAllProgressBar.setValue(imp.getCurrentSlice());
        OverAllProgressBar.setValue(OverAllProgressBar.getValue()+advance);
return;
    }


    private class VideoReader extends java.awt.Frame implements Runnable {

        File file = null;
        boolean success = false;
        boolean read = true;
        double height = 0.0;
        double width = 0.0;
        double totalFrames = 0.0;
        double posFrame = 0.0;
        double fps = 0.0;
        int buffSize = 10; //250 frames, i.e., for a 25 fps, 10 seconds worth of frames to score.
        ImagePlus imp = null; //this imageplus has to be shared between 2 threads?
        VideoCapture cap = null;

        public VideoReader(File ImgFile) {
            file = ImgFile;
            this.loadOpenCVdependencies();
            this.openVideo();
        }

        @Override
        public void run() {
            System.out.println("VideoReader Thread RUN");
            if (success && read) {
                try {
                    ImageStack is = this.makeBufferedStack(buffSize);
                    ImagePlus tempImp = new ImagePlus("", is);                        
                    synchronized (this) {
                        for(int i = 0; i < buffSize; i++){
                        imp.getStack().deleteSlice(1);
//                        imp.getStack().addSlice(is.);
                                }
                    }
                } catch (IOException ex) {
                    Logger.getLogger(Scoring_Assistant.class.getName()).log(Level.SEVERE, null, ex);
                }
            } else {
                ij.IJ.showMessage("Error", "Error opening/reading video file.");
            }
        }

//is this the best way to go about it? <- it needs to be done once.
        private void loadOpenCVdependencies() {
            System.loadLibrary(Core.NATIVE_LIBRARY_NAME);
        }

        public void openVideo() {
            cap = new VideoCapture(file.getAbsolutePath());
            if (cap.isOpened()) {
                System.out.println("Video opened.");
                //read video file using opencv
                height = cap.get(CAP_PROP_FRAME_HEIGHT); //height
                width = cap.get(CAP_PROP_FRAME_WIDTH); //width
                //double format = cap.get(CAP_PROP_FORMAT); //0.0 <- ?
                //double codecPixFormat = cap.get(CAP_PROP_CODEC_PIXEL_FORMAT); //8.08E8 <- ?
                //double buffsize = cap.get(CAP_PROP_BUFFERSIZE); //0
                posFrame = cap.get(CAP_PROP_POS_FRAMES); //0
                fps = cap.get(CAP_PROP_FPS); //25
                totalFrames = cap.get(CAP_PROP_FRAME_COUNT); //3715 <- checks out - got 3700 for 2.28 vid of 25fps         
                System.out.println("Height: " + height + " width: " + width);
                success = true;
            } else {
                System.out.println("Error opening video");
                success = false;
            }
        }

        public BufferedImage Mat2BufferedImage(Mat mat) throws IOException {
            //Encoding the image
            MatOfByte matOfByte = new MatOfByte();
            Imgcodecs.imencode(".jpg", mat, matOfByte);
            //Storing the encoded Mat in a byte array
            byte[] byteArray = matOfByte.toArray();
            //Preparing the Buffered Image
            InputStream in = new ByteArrayInputStream(byteArray);
            BufferedImage bufImage = ImageIO.read(in);
            return bufImage;
        }

        public ImageStack makeBufferedStack(int noOfFrames) throws IOException {
            ImageStack is = new ImageStack();
            Mat image = null;
            BufferedImage buff = null;
            ImagePlus tempImp = null;
            int idx = 0;
            do {
                idx = idx + 1;
                image = new Mat();
                read = cap.read(image);
//                System.out.println("iter no.: " + idx + " read bool: " + read);
                //create a buffered image                   
                buff = Mat2BufferedImage(image);
                tempImp = new ImagePlus(String.valueOf(idx), buff);
                // tempImp.show();
                is.addSlice(tempImp.getProcessor());
            } while (idx < noOfFrames);
            posFrame = cap.get(CAP_PROP_POS_FRAMES);                
            return is;
        }

        public synchronized ImagePlus getStackBuff() {
            return imp;
        }
        
        public void setStackBuff(){
            if (success && read) {
                try {
                    ImageStack is = this.makeBufferedStack(150);
                    synchronized (this) {
                        imp = new ImagePlus("Video stack1", is);
                    }
                } catch (IOException ex) {
                    Logger.getLogger(Scoring_Assistant.class.getName()).log(Level.SEVERE, null, ex);
                }
            } else {
                ij.IJ.showMessage("Error", "Error opening/reading video file.");
            }
        }
    }

}
